name = "twinurl"
main = "src/index.js"
compatibility_date = "2025-02-21"

# KV Namespace Binding
[[kv_namespaces]]
binding = "KV"
id = "dda1f45e316a46019b916790a4d226ec"  # Create a KV database and put the id of here

# Environment Variables
[vars]
SECRET_CODE = ""
